import { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import {
  FiDownload,
  FiCopy,
  FiTrash2,
  FiEye,
  FiEyeOff,
  FiUser,
  FiArrowLeft,
} from "react-icons/fi";
import toast from "react-hot-toast";
import axios from "axios";
import Loader from "../components/Loader";

const ImagePage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [image, setImage] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchImage = async () => {
      setLoading(true);
      try {
        const { data } = await axios.get(
          `${import.meta.env.VITE_BACKEND_BASE_URL}/api/image/${id}`,
          {
            headers: {
              Authorization: `Bearer ${localStorage.getItem("token")}`,
            },
          },
        );
        setImage(data.data.image);
      } catch (error) {
        toast.error("Failed to load image or it does not exist.");
        navigate("/gallery");
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchImage();
    }
  }, [id, navigate]);

  const handleDownload = () => {
    if (!image) return;
    const link = document.createElement("a");
    link.href = image.imageUrl;
    link.download = `imagiverse-${image._id}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("Image download started!");
  };

  const handleCopyPrompt = () => {
    if (!image) return;
    navigator.clipboard.writeText(image.prompt);
    toast.success("Prompt copied to clipboard!");
  };

  const handleDelete = async () => {
    if (
      !image ||
      !window.confirm("Are you sure you want to permanently delete this image?")
    )
      return;

    try {
      await axios.delete(
        `${import.meta.env.VITE_BACKEND_BASE_URL}/api/image/${image._id}`,
        {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          },
        },
      );
      toast.success("Image deleted successfully!");
      navigate("/my-images");
    } catch (error) {
      toast.error("Failed to delete image.");
    }
  };

  if (loading) return <Loader />;
  if (!image) return null;

  const aspectRatio =
    image.width && image.height ? image.width / image.height : 1;

  const modelNameMap = {
    "google/gemini-2.5-flash:free": "Gemini 2.5 Flash (Free)",
    "fal-ai/nano-banana": "Nano Banana (New)",
    "openai/gpt-image-1.5:free": "GPT Image 1.5 (Free)",
    "google/nano-banana-2:free": "Nano Banana 2 (New)",
    "black-forest-labs/FLUX.1-krea-dev": "Flux.1 Krea Dev (New)",
    "black-forest-labs/FLUX-2-klein-4b:free": "Flux.2 Klein 4B (Free)",
    "black-forest-labs/FLUX.1-depth": "Flux.1 Depth",
    "black-forest-labs/FLUX.1-schnell-Free": "Flux.1 Schnell (Free)",
    "black-forest-labs/FLUX.1-dev": "Flux.1 Dev",
    "stabilityai/sdxl-turbo:free": "SDXL Turbo",
    "lodestones/Chroma:free": "Chroma - Free (Unstable)",
    "HiDream-ai/HiDream-I1-Full:free": "HiDream i1 Full",
    "fal-ai/minimax/image-01": "Minimax Image-01",
  };
  const modelDisplayName =
    modelNameMap[image.model] || image.model || "Unknown";

  const username =
    image.user?.username ||
    image.user?.name?.toLowerCase().replace(/\s+/g, "") ||
    "unknown_user";

  return (
    <div className="bg-[#202142] text-white min-h-[calc(100vh-80px)] p-4 sm:p-8 flex justify-center items-start font-['Poppins']">
      <div className="relative w-full max-w-5xl bg-black/20 p-4 sm:p-6 rounded-xl border border-white/10 shadow-lg animate-fade-in">
        <button
          onClick={() => navigate("/gallery")}
          className="absolute top-8 left-8 p-2 rounded-full bg-black/40 hover:bg-black/20 transition-colors cursor-pointer"
        >
          <FiArrowLeft className="text-2xl" />
        </button>
        <div className="flex justify-center items-center">
          <img
            src={image.imageUrl}
            alt={"Generated Image"}
            className="max-w-full max-h-[80vh] rounded-lg shadow-md shadow-black/20 object-fill"
            style={{ aspectRatio }}
          />
        </div>

        <div className="mt-6">
          <h2 className="text-xl sm:text-2xl font-bold text-white">
            Generated Prompt
          </h2>
          <p className="mt-3 text-gray-300 font-['JetBrains_Mono'] text-sm sm:text-base sm:leading-relaxed">
            {image.prompt}
          </p>
        </div>

        {image.user && (
          <div className="mt-6 pt-6 border-t border-white/10">
            <h2 className="text-lg font-bold text-white mb-4">Generated By</h2>
            <div className="flex items-center gap-4">
              <div className="flex items-center justify-center w-12 h-12 rounded-full bg-[#8A4FFF]/10 border border-white/10">
                {image.user.image ? (
                  <img
                    src={image.user.image}
                    className="w-11 h-11 rounded-full text-[#8A4FFF]"
                  />
                ) : (
                  <FiUser className="w-6 h-6 text-[#8A4FFF]" />
                )}
              </div>
              <div>
                <Link
                  to={`/${image.user.username}`}
                  className="font-semibold text-lg text-[#8A4FFF] hover:underline hover:opacity-70"
                >
                  {image.user.name}
                </Link>
                <p className="text-sm text-gray-400">@{username}</p>
              </div>
            </div>
          </div>
        )}

        <div className="mt-6 pt-6 border-t border-white/10">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 text-center sm:text-left">
            <div>
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                Model
              </p>
              <p
                className="mt-1 text-sm sm:text-base text-gray-200 truncate"
                title={modelDisplayName}
              >
                {modelDisplayName}
              </p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                Dimensions
              </p>
              <p className="mt-1 text-sm sm:text-base text-gray-200">
                {image.width} x {image.height} px
              </p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                Generation Time
              </p>
              <p className="mt-1 text-sm sm:text-base text-gray-200">
                {image.generationTime
                  ? `${(image.generationTime / 1000).toFixed(1)}s`
                  : "N/A"}
              </p>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                Visibility
              </p>
              <div className="mt-1 flex items-center justify-center sm:justify-start gap-2 text-sm sm:text-base text-gray-200">
                {image.isPublic ? <FiEye /> : <FiEyeOff />}
                <span>{image.isPublic ? "Public" : "Private"}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-6 pt-6 border-t border-white/10 flex flex-wrap justify-between items-center gap-4">
          <div className="flex items-center gap-3">
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 py-2 px-4 rounded-lg border border-[#8A4FFF] text-[#8A4FFF] transition-colors duration-300 hover:bg-[#8A4FFF] hover:text-white"
            >
              <FiDownload size={18} />
              <span className="font-semibold text-sm">Download</span>
            </button>
            <button
              onClick={handleCopyPrompt}
              className="flex items-center gap-2 py-2 px-4 rounded-lg border border-gray-600 text-gray-300 transition-colors duration-300 hover:bg-gray-600 hover:text-white"
            >
              <FiCopy size={18} />
              <span className="font-semibold text-sm">Copy Prompt</span>
            </button>
          </div>

          {image.isOwner && (
            <button
              onClick={handleDelete}
              className="flex items-center gap-2 py-2 px-4 rounded-lg bg-red-600/20 border border-red-600/50 text-red-400 transition-colors duration-300 hover:bg-red-600 hover:text-white"
              title="Delete Image"
            >
              <FiTrash2 size={18} />
              <span className="font-semibold text-sm">Delete</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default ImagePage;
